# conda build -b .

# increment build number when updating hash
{% set git_hash = "6052a8a" %}
{% set build_number = "0" %}

package:
  name: mlir
  version: 13.0

source:
  git_url: https://github.com/llvm/llvm-project.git
  git_rev: {{ git_hash }}
  git_depth: 1

build:
  number: {{ build_number }}
  string: g{{ git_hash }}_{{ build_number }}

requirements:
  host:
    - cmake
    - ninja
    - python
    - ncurses
    - zlib
  run:
    - zlib
    - ncurses

test:
  commands:
    - $PREFIX/bin/mlir-opt --version

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: mlir/LICENSE.TXT
  summary: LLVM build for MLIR
