# increment build number when updating hash
{% set git_hash = "3bcca6b" %}
{% set build_number = "0" %}

package:
  name: mlir
  version: 12.0

source:
  git_url: https://github.com/llvm/llvm-project.git
  git_rev: {{ git_hash }}
  git_depth: 1

build:
  number: {{ build_number }}
  string: g{{ git_hash }}_{{ build_number }}

requirements:
  build:
    #- {{ compiler('c') }} # [unix]
    #- {{ compiler('cxx') }} # [unix]
    - cmake
    - ninja
    - python >=3

test:
  requires:
    - python
  commands:
    - $PREFIX/bin/mlir-opt --version

about:
  home: http://llvm.org/
  dev_url: https://github.com/llvm-mirror/llvm
  license: NCSA
  license_file: mlir/LICENSE.TXT
  summary: LLVM build for MLIR
